### PR TITLE
Add transpose function to transpose dataset rows with columns

### PR DESCRIPTION
**Pull request by scottlowe**

### CODE REVIEW

**Comment by RickMoynihan** [comment]
Nice!!! 👍 👍 👍 

Thanks @scottlowe this will make a valuable addition.

Firstly a minor issue, it would be good if the docstring said that this is eager and will load everything into memory.

Secondly some things to discuss before merging...  These are really more to do with Grafter than the specific PR... In particular surrounding the thorny issue of header rows...

Should we move the data for the first row into the column headers, as headers aren't supposed to be part of the data.  For example when you load a dataset you get unique assigned headers, and you opt in to setting the headers yourself... You can say `move-first-row-to-header`.  Obviously this is a reshaping operation like melt, so it has an impact on the header.

For example in the docstring:

````
| :a | :b | :c | :d | :e | :f |
|----+----+----+----+----+----|
|  1 |  2 |  3 |  4 |  5 |  6 |
|  9 | 10 | 11 | 12 | 13 | 14 |

| :a | 1 |  9 |
|----+---+----|
| :b | 2 | 10 |
| :c | 3 | 11 |
| :d | 4 | 12 |
| :e | 5 | 13 |
| :f | 6 | 14 |
````

Which seems a little strange as we now have some of our data in the header....  Would this be better, i.e. moving the original header into the data, and generating a new header (as we do for new datasets):

````
| a  | b |  c |
|----+---+----|
| :a | 1 |  9 |
| :b | 2 | 10 |
| :c | 3 | 11 |
| :d | 4 | 12 |
| :e | 5 | 13 |
| :f | 6 | 14 |
````

Also transposing twice is really weird... what you want is something like this:

````
| :a | :b | :c | :d | :e | :f |
|----+----+----+----+----+----|
|  1 |  2 |  3 |  4 |  5 |  6 |
|  9 | 10 | 11 | 12 | 13 | 14 |

| a  | b |  c |
|----+---+----|
| :a | 1 |  9 |
| :b | 2 | 10 |
| :c | 3 | 11 |
| :d | 4 | 12 |
| :e | 5 | 13 |
| :f | 6 | 14 |

| :a | :b | :c | :d | :e | :f |
|----+----+----+----+----+----|
|  1 |  2 |  3 |  4 |  5 |  6 |
|  9 | 10 | 11 | 12 | 13 | 14 |
````

i.e. something that round trips.  Currently I think what you'll get is a bit of a mess...  I'm not sure we can really solve this without having an orientation property on the dataset that lets you flip this... I'm pretty sure R does this.  I think we should consider this when we move away from old style incanter Datasets to the core.matrix Dataset protocol.

Without having an orientation it would probably still be good to have a transposition the other way (if this is clockwise, it would be good to have counterclockwise) i.e. converting the first row to a column of data.

Also all of this brings up providing better/new methods of moving data from headers into data and vice versa... e.g. if we left the behaviour as you have it you could do:

`(-> ds transpose move-header-to-first-row)`

I guess `move-header-to-first-row` might default to providing a generated excel like set of column names, but it should probably also allow you to set a new one.

Anyway it's probably worth having a discussion about this - I don't think we can solve all this immediately though.

**Comment by RickMoynihan** [comment]
Sorry didn't mean to close

**Comment by RickMoynihan** [comment]
One other thing, more for consistency than anything else it would be good to include the transpose function in the top level tabular namespace as we do for the other tabular functions like [melt](https://github.com/Swirrl/grafter/blob/master/src/tabular/grafter/tabular.clj#L34).

**Comment by scottlowe** [comment]
> Should we move the data for the first row into the column headers, as headers aren't supposed to be part of the data

Yes, that's a good question. My main use case at the moment is for a dataset where the first column of the input dataset is really "row-labels", so in my specific case, it makes sense to move that into the header row; but I take your point that it may not be expected or what another consumer would want for a more regular transposition.

Oddly enough, the function is made more complex by that header row requirement, and the case that you desire is probably simpler to implement given that the function already does this for the `rest` of the rows. 😃 .

We should definitely discuss this further - probably more efficient to do that verbally and offline rather than type here. Certainly, I looked all over (also in Incanter) for this function and it's not available elsewhere.

Anyway, we could always pass a flag as you suggested, or have 2 different functions which cover these two variations. The former sounds more desirable.

**Pull request closed without merging**
