### PR TITLE
Extend `query` ::repo arg spec to IPrepareQuery

### PR DESCRIPTION
**Pull request by andrewmcveigh**
So that we can `query` anything that implements IPrepareQuery

### CODE REVIEW

**Comment by RickMoynihan** [comment]
This sounds like a good idea.  What exactly are you wanting it for?

**Comment by andrewmcveigh** [comment]
In particular, this https://github.com/Swirrl/drafter/pull/341/files#diff-ca50593159f7e3b216af65f1c773bdc9R242

**Comment by andrewmcveigh** [comment]
But also, seeing as the spec is overly tight, a kind of correction (we only use `pr/prepare-query` atm)

**Comment by RickMoynihan** [comment]
Agreed.  Thanks for the PR.  Merged.

**Pull request merged**
